### ISSUE TITLE
Timestamps are not formatted

### ISSUE THREAD

**Issue by andersespedalen** [thijssimonis/nova-list-card#4]
Outputting timestamps (like `created_at`)  shows as YYYY-MM-DDTHH:MM:SS.000000Z

**Comment by SyamsulHasriTamrin** [comment]
yup, the timestamps not formatted, it's better to include the format functions

**Comment by thijssimonis** [comment]
If your collection holds eloquent models then you can format it in your model to the your wanted format, but most of the times this break other code. You also can remap the collection with the `map` method to a other key and format it like this:

```php
(new NovaListCard())
    ->title(__('5 latest users'))
    ->rows(
        User::select('email', 'created_at')
            ->orderBy('created_at', 'DESC')
            ->limit(5)->get()
            ->map(function($row) {
                $row['created'] = $row['created_at']->format('d-m-Y');
                unset($row['created_at']);

                return $row;
            })
    ),
```

If you know a better method feel free to create a PR.
